version: '3'

tasks:
  apply-seeds:
    cmds:
      - mix run priv/repo/seeds.exs

  build-prod:
    cmds:
      - task: stop-prod
      - MIX_ENV=prod mix release --overwrite
      - task: normalize-release-eol
      - task: start-prod
    env:
      MIX_ENV: prod

  normalize-release-eol:
    desc: "Strip CRLF and ensure exec bits on release scripts"
    cmds:
      - |
        set -eu
        files=(
          "_build/prod/rel/fast_api/releases/"*/"env.sh"
          "_build/prod/rel/fast_api/bin/fast_api"
          "_build/prod/rel/fast_api/bin/"*
        )
        for f in "${files[@]}"; do
          [ -f "$f" ] || continue
          sed -i 's/\r$//' "$f"
          chmod +x "$f"
        done

  deps:
    cmds:
      - mix deps.get

  deps-update:
    cmds:
      - mix deps.update --all

  gen-seeds:
    cmds:
      - mix run priv/repo/gen-seeds.exs
    env:
      MIX_ENV: prod

  load-env:
    cmds:
      - source .env

  lint:
    cmds:
      - mix dialyzer
      - mix credo
    env:
      MIX_ENV: test

  migrate:
    cmds:
      - mix ecto.migrate
    env:
      MIX_ENV: dev

  migrate-prod:
    deps: [load-env]
    cmds:
      - mix ecto.migrate
    env:
      MIX_ENV: prod

  run-dev:
    cmds:
      - iex -S mix phx.server
    env:
      MIX_ENV: dev

  restart-prod:
    cmds:
      - task: stop-prod
      - task: start-prod

  start-prod:
    cmds:
      - _build/prod/rel/fast_api/bin/fast_api daemon

  stop-prod:
    cmds:
      - ps -ea -o pid,command | grep [e]lixir | awk '{print $1}' | xargs kill -9

  local-env-down:
    cmds:
      - docker compose -f $(pwd)/docker/docker-compose.yaml down --remove-orphans

  local-env-up:
    cmds:
      - docker compose -f $(pwd)/docker/docker-compose.yaml up -d

  local-env:
    cmds:
      - task: load-env
      - task: local-env-down
      - task: local-env-up
      # - task: seed

  seed:
    cmds:
      - mix run priv/repo/seeds.exs
    env:
      MIX_ENV: dev
