version: '3'

tasks:
  apply-seeds:
    cmds:
      - mix run priv/repo/seeds.exs

  build-prod:
    cmds:
      - mix release
    env:
      MIX_ENV: prod

  deps:
    cmds:
      - mix deps.get

  deps-update:
    cmds:
      - mix deps.update --all

  gen-seeds:
    cmds:
      - mix run priv/repo/gen-seeds.exs
    env:
      MIX_ENV: prod

  lint:
    cmds:
      - mix dialyzer
      - mix credo
    env:
      MIX_ENV: test

  run-dev:
    cmds:
      - mix phx.server
    env:
      MIX_ENV: test

  restart-prod:
    cmds:
      - task: stop-prod
      - task: start-prod

  start-prod:
    cmds:
      - _build/prod/rel/fast_api/bin/fast_api daemon

  stop-prod:
    cmds:
      - ps -ea -o pid,command | grep [e]lixir | awk '{print $1}' | xargs kill -9

  local-env:
    cmds:
      - docker compose -f $(pwd)/docker/docker-compose.yaml down --remove-orphans
      - docker compose -f $(pwd)/docker/docker-compose.yaml up -d
