version: '3.9'

services:
  mongo:
    image: mongo:4.4.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - test-network
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - test-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
  spreadsheet_sync:
    image: spreadsheet_sync
    environment:
      - DISABLE_SPREADSHEET_SYNC=true
      - MONGO_USERNAME=mongo
      - MONGO_PASSWORD=mongo
      - MONGO_HOST=mongo
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  postgres:
  mongo:
